export enum IColor {
  AZUL = "AZUL",
  BLANCO = "BLANCO",
  CELESTE = "CELESTE",
  NEGRO = "NEGRO",
  VERDE = "VERDE",
  MULTICOLOR = "MULTICOLOR",
  NARANJA="NARANJA",
  ROJO = "ROJO",
  ROSA = "ROSA",
  MARRON = "MARRON",
  AMARILLO = "AMARILLO",
  VIOLETA = "VIOLETA",
  GRIS = "GRIS"
}
